# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# ====================================================
# Advanced Data Mining Project - Deliverable 1
# Data Collection, Cleaning, and Exploration
# ====================================================

# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization style
sns.set(style="whitegrid")

# ====================================================
# Step 1: Load Dataset
# ====================================================

df = pd.read_excel("/content/online_retail_II.xlsx")

# Display first few rows
print("First 5 Rows of Dataset:")
print(df.head())

# ====================================================
# Step 2: Inspect Dataset Structure
# ====================================================

print("\nDataset Information:")
print(df.info())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Data Types:")
print(df.dtypes)

# Summary statistics
print("\nSummary Statistics:")
print(df.describe())

# ====================================================
# Step 3: Check Missing Values
# ====================================================

print("\nMissing Values in Each Column:")
print(df.isnull().sum())

# ====================================================
# Step 4: Handle Missing Values
# ====================================================

# Fill missing CustomerID values with 0
df['Customer ID'] = df['Customer ID'].fillna(0)

# Drop rows where Description is missing
df = df.dropna(subset=['Description'])

# Verify missing values again
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

# ====================================================
# Step 5: Remove Duplicate Records
# ====================================================

print("\nNumber of Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates Removed")

# ====================================================
# Step 6: Detect and Handle Outliers
# ====================================================

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Quantity'])
plt.title("Boxplot of Quantity (Outlier Detection)")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Price'])
plt.title("Boxplot of Unit Price (Outlier Detection)")
plt.show()

# Remove extreme outliers using IQR method
Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df['Price'] >= lower_bound) & (df['Price'] <= upper_bound)]

# ====================================================
# Step 7: Exploratory Data Analysis (EDA)
# ====================================================

# Convert InvoiceDate to datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Create Sales column
df['Sales'] = df['Quantity'] * df['Price']

# ====================================================
# Sales Distribution
# ====================================================

plt.figure(figsize=(8,5))
sns.histplot(df['Sales'], bins=50, kde=True)
plt.title("Distribution of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.show()

# ====================================================
# Top 10 Products by Sales
# ====================================================

top_products = df.groupby('Description')['Sales'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
top_products.plot(kind='bar')
plt.title("Top 10 Products by Sales")
plt.ylabel("Total Sales")
plt.xlabel("Product")
plt.show()

# ====================================================
# Sales by Country
# ====================================================

country_sales = df.groupby('Country')['Sales'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
country_sales.plot(kind='bar')
plt.title("Top Countries by Sales")
plt.xlabel("Country")
plt.ylabel("Total Sales")
plt.show()

# ====================================================
# Correlation Heatmap
# ====================================================

plt.figure(figsize=(8,6))
corr = df[['Quantity','Price','Sales']].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

# ====================================================
# Scatter Plot (Quantity vs Sales)
# ====================================================

plt.figure(figsize=(8,6))
sns.scatterplot(x=df['Quantity'], y=df['Sales'])
plt.title("Quantity vs Sales Relationship")
plt.xlabel("Quantity")
plt.ylabel("Sales")
plt.show()
# ====================================================
# Final Dataset Shape After Cleaning
# ====================================================

print("\nFinal Dataset Shape After Cleaning:")
print(df.shape)

print("\nData Cleaning and Exploration Completed Successfully.")